FROM node:latest

WORKDIR /var/www/react

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL ${REACT_APP_API_URL}
ARG REACT_APP_AUTH_ENABLED
ENV REACT_APP_AUTH_ENABLED ${REACT_APP_AUTH_ENABLED}

RUN npm install -g serve

ENTRYPOINT [ "serve",  "-s", "." ]